### ISSUE TITLE
Maybe add QoS struct

### ISSUE THREAD

**Issue by alephzero** [alephzero/alephzero#102]
The subscriber constructor is overly verbose.
```cpp
a0::Subscriber sub(
    "topic",
    A0_INIT_AWAIT_NEW,  // or MOST_RECENT or OLDEST
    A0_ITER_NEWEST,     // or NEXT
    callback);
```

I'd like to move INIT and ITER into an optional QoS struct. I'm thinking a good default: (AWAIT_NEW, NEXT)
Do you think that matches most people's expectations?

I'm likely to keep/add several C++ overloads, including a backwards compatible one for now.

```cpp
a0::Subscriber sub("topic", callback);
a0::Subscriber sub("topic", qos, callback);
a0::Subscriber sub("topic", init, iter, callback);
```

Thoughts?

**Comment by macmason** [comment]
LGTM.

I can imagine the common-but-not-default case looking something like this:

```
a0::Subscriber sub(
  "foo",
  a0::Qos{
    .init = A0_NON_DEFAULT,
    .iter = A0_OTHER_NON_DEFAULT,
  },
  cb
);  
```

which feels pretty good. Leaving the current behavior in place for a few releases is a good idea, just to ease the transition.
