### ISSUE TITLE
a0_transport_remove_head() funticon

### ISSUE THREAD

**Issue by snowinli** [alephzero/alephzero#82]
1. void a0_transport_remove_head(a0_locked_transport_t lk, a0_transport_state_t* state):
 Is state->high_water_mark right for updating?:
      if no next head when state->high_water_mark == head_end ?, following:
      1.1  Maybe state->high_water_mark be update to prev head tail?
      1.2 if crash after  a0_transport_commit(lk),  then state->seq_low++  is not consistent with  state->seq_high.
2.void a0_transport_evict:
  Maybe:
  while(){ 
          ...
         state = a0_transport_working_page(lk);
  }

**Comment by alephzero** [comment]
Sorry for the delay. I wasn't getting emails from github issues.

Are you `high_water_mark` isn't tracked in the master branch. Are you referring to the dev branch?

I'm not sure I follow your question.
The `high_water_mark` is bound to a state page, along with `seq_low` and `seq_high`. They should change in lock-step.
If allocating a new frame requires an eviction of an old frame, the old frame is removed, in the working state page, the removal is committed, and pages swap.

Can you please clarify your question or concern?

**Comment by snowinli** [comment]
sorry，I read my email today.
It is not important.&nbsp;
May get workingstate again after remove ,or not.
important qestion:
If I replace all uint64 seq with uint8 seq(low_seq,high_seq), do easily, when seq++ is overflow to 0, read process will lost some messages(data),&nbsp; I have trired,I am sure,&nbsp;
I use rpc.c code(not rpc.cpp) to test seq overflow question, but not reply,because I need IPC in fact.
sorry,I don't speek english good.
&nbsp; thanks.



---Original---
From: ***@***.***&gt;
Date: Thu, Sep 16, 2021 12:41 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [alephzero/alephzero] a0_transport_remove_head() funticon (#82)




 
Sorry for the delay. I wasn't getting emails from github issues.
 
Are you high_water_mark isn't tracked in the master branch. Are you referring to the dev branch?
 
I'm not sure I follow your question.
 The high_water_mark is bound to a state page, along with seq_low and seq_high. They should change in lock-step.
 If allocating a new frame requires an eviction of an old frame, the old frame is removed, in the working state page, the removal is committed, and pages swap.
 
Can you please clarify your question or concern?
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by alephzero** [comment]
Overflow of sequence numbers is not handled. `uint64` is used because they are very hard to overflow.
Why do you want to use `uint8` and not `uint64`? Are you on an embedded device?

**Comment by snowinli** [comment]
I am just on an embedded device.
I forgot uint64 is a large number, feel&nbsp; overflow is a problem,&nbsp; uint64 is hard to overflow, so I simulaor overflow with uint8, found it is a problem, then I start to think a way to resolve it.
&nbsp;I have thought to replace seq with read_off, read_off is speed a little lower than seq,because it need check all reader'read_off with for loop.
&nbsp;monitor programm may read and monitor all reader's read_off.
My ipc have only two or three reader, so I have used read_off.





---Original---
From: ***@***.***&gt;
Date: Wed, Sep 29, 2021 02:00 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [alephzero/alephzero] a0_transport_remove_head() funticon (#82)




 
Overflow of sequence numbers is not handled. uint64 is used because they are very hard to overflow.
 Why do you want to use uint8 and not uint64? Are you on an embedded device?
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by snowinli** [comment]
If I early read your email, perhaps I don't think read_off.



---Original---
From: ***@***.***&gt;
Date: Wed, Sep 29, 2021 02:00 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [alephzero/alephzero] a0_transport_remove_head() funticon (#82)




 
Overflow of sequence numbers is not handled. uint64 is used because they are very hard to overflow.
 Why do you want to use uint8 and not uint64? Are you on an embedded device?
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
