### ISSUE TITLE
Is alephzero stable enough for production?

### ISSUE THREAD

**Issue by pi1ot** [alephzero/alephzero#83]
Is alephzero stable enough for production?
Thanks.

**Comment by alephzero** [comment]
Sorry for the delay. I wasn't getting emails from github issues.

It's been used in production for >2 years over at ThirdWave.
The current master hasn't been touched in a long time and has been stable.

I've been doing development on a dev branch that is not backwards compatible, but only syntactic changes, no correctness.
Pretty soon I'm going to rename the current master as v0.2 and the dev branch as v0.3, turning that into master.

I'm happy to keep you in the loop with changes and transitions, before making any breaking changes.
