### ISSUE TITLE
if arena.workstate.seq_high++ is overflow?

### ISSUE THREAD

**Issue by snowinli** [alephzero/alephzero#84]
if arena.workstate.seq_high++ is overflow,  transport.seq is invalid for long time, and some messages which are to be read cannot be read forever.  arena.workstate.seq_low++ is also overflow, even uint64_t.

**Comment by alephzero** [comment]
I'm not sure I understand.

The max value for uint64_t is 18,446,744,073,709,551,615. If you send a million messages a second, it'll take 584,942 years to overflow.

Is there a particular snippet you think is at risk of overflowing in normal operation?

**Comment by snowinli** [comment]
sorry, I should consider to calculate this uint64 value.
It is not problem.


These days I have placed read_off in arena struct.
If write removed head, read_off will maybe invalid off. If invalid, so read_off reset to 0, next time read from new head_off. I designed so, runned.



---Original---
From: ***@***.***&gt;
Date: Thu, Sep 16, 2021 12:31 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [alephzero/alephzero] if arena.workstate.seq_high++ is overflow? (#84)




 
I'm not sure I understand.
 
The max value for uint64_t is 18,446,744,073,709,551,615. If you send a million messages a second, it'll take 584,942 years to overflow.
 
Is there a particular snippet you think is at risk of overflowing in normal operation?
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by alephzero** [comment]
What is the goal of adding `read_off` to the arena struct?

**Comment by snowinli** [comment]
1.tommorrow I have other problem, I have modified it about remove logic, I will send tommorrow the modifide function code.
2. By read_off, when all readers have read off_tail, I can reset off_head to top(workingoff) , write data from top again orderly, or else evict forever.







---Original---
From: ***@***.***&gt;
Date: Wed, Sep 29, 2021 02:03 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [alephzero/alephzero] if arena.workstate.seq_high++ is overflow? (#84)




 
What is the goal of adding read_off to the arena struct?
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by snowinli** [comment]
I use dev branch(branch date:20210908).



---Original---
From: ***@***.***&gt;
Date: Wed, Sep 29, 2021 02:03 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [alephzero/alephzero] if arena.workstate.seq_high++ is overflow? (#84)




 
What is the goal of adding read_off to the arena struct?
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by snowinli** [comment]
one scene:&nbsp;
&nbsp; write crashed, then write restart, want to&nbsp; delete old data(control system),&nbsp; so set seq_low=seq_high=0,&nbsp; then wrote 20 datas, just reader'seq is 10, then reader will maybe crash when read next data,&nbsp; but read_off will be no problem.



---Original---
From: ***@***.***&gt;
Date: Wed, Sep 29, 2021 02:03 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [alephzero/alephzero] if arena.workstate.seq_high++ is overflow? (#84)




 
What is the goal of adding read_off to the arena struct?
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by snowinli** [comment]
In function&nbsp;a0_transport_alloc(...)：&nbsp; &nbsp;Need add the following code above function&nbsp;a0_transport_evict(...), example:
a0_err_t a0_transport_alloc(...)
{
	...
&nbsp;&nbsp;
&nbsp; bool tail_space_full;
&nbsp; A0_RETURN_ERR_ON_ERR(a0_transport_find_slot(lk, frame_size, &amp;off, &amp;tail_space_full));
&nbsp; //snowli new add code:
&nbsp; if(tail_space_full)
&nbsp; {
	&nbsp; &nbsp;if(state-&gt;off_tail < state-&gt;off_head)
	&nbsp; &nbsp;{
			// tail ptr is above head ptr
		&nbsp; state-&gt;off_head =a0_transport_workspace_off();
	&nbsp; &nbsp;}
&nbsp; }
&nbsp;&nbsp;
	
	if(a0_transport_evict(...) || tail_space_full){
		a0_transport_commit(lk);
&nbsp; }
&nbsp;}


A0_STATIC_INLINE
a0_err_t a0_transport_find_slot(a0_transport_locked_t lk, size_t frame_size, size_t* off, bool* tail_space_full) {
&nbsp; a0_transport_hdr_t* hdr = (a0_transport_hdr_t*)lk.transport-&gt;_arena.buf.ptr;
&nbsp; a0_transport_state_t* state = a0_transport_working_page(lk);


&nbsp; *tail_space_full=false;
&nbsp; bool empty;
&nbsp; A0_RETURN_ERR_ON_ERR(a0_transport_empty(lk, &amp;empty));


&nbsp; if (empty) {
&nbsp; &nbsp; *off = a0_transport_workspace_off();
&nbsp; } else {
&nbsp; &nbsp; *off = a0_max_align(a0_transport_frame_end(hdr, state-&gt;off_tail));
&nbsp; &nbsp; //snowli modify, remove "="
&nbsp; &nbsp; //if (*off + frame_size &gt;= hdr-&gt;arena_size)
&nbsp; &nbsp; if (*off + frame_size &gt; hdr-&gt;arena_size) {
		// need start from top
&nbsp; &nbsp; &nbsp; *off = a0_transport_workspace_off();
	&nbsp; // snowli new add code
&nbsp; &nbsp; &nbsp; *tail_space_full = true;
&nbsp; &nbsp; }
&nbsp; }


&nbsp; if (*off + frame_size &gt; hdr-&gt;arena_size) {
&nbsp; &nbsp; return A0_ERRCODE_TRANSPORT_FRAME_GT_ARENA;
&nbsp; }


&nbsp; return A0_OK;
}




&nbsp; &nbsp; &nbsp; &nbsp;
   transport_alloc

**Comment by snowinli** [comment]
A0_STATIC_INLINE
void a0_transport_evict(a0_locked_transport_t lk, size_t off, size_t frame_size) {
&nbsp; size_t head_off;
&nbsp; size_t head_size;
&nbsp; a0_transport_state_t* state = a0_transport_working_page(lk);
&nbsp; while (a0_transport_head_interval(lk, state, &amp;head_off, &amp;head_size) &amp;&amp;
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;a0_transport_frame_intersects(off, frame_size, head_off, head_size)) {
&nbsp; &nbsp; a0_transport_remove_head(lk, state);
	//snowli add new
	state = a0_transport_working_page(lk);
&nbsp; }
}

**Comment by snowinli** [comment]
Because no new data is wrote when do a0_transport_evict, may not broadcast ;
When finish wrote , before unlock,&nbsp; commit and broadcast.
!! : afraid process is crash, data happed none 0 none 1 value,
and I typedef bool committed_page_idx, not size_t committed_page_idx.


example:
a0_err_t a0_transport_commit_not_broadcast(a0_transport_locked_t lk) {
&nbsp; &nbsp; a0_transport_hdr_t* hdr = (a0_transport_hdr_t*)lk.transport-&gt;_arena.buf.ptr;
&nbsp; &nbsp; // Assume page A was the previously committed page and page B is the working
&nbsp; &nbsp; // page that is ready to be committed. Both represent a valid state for the
&nbsp; &nbsp; // transport. It's possible that the copying of B into A will fail (prog crash),
&nbsp; &nbsp; // leaving A in an inconsistent state. We set B as the committed page, before
&nbsp; &nbsp; // copying the page info.
&nbsp; &nbsp; a0_transport_states_area_t* states = a0_transport_states_area(lk);
&nbsp; &nbsp; states-&gt;committed_page_idx = !states-&gt;committed_page_idx;
&nbsp; &nbsp; states-&gt;state_pages[!states-&gt;committed_page_idx]=states-&gt;state_pages[!!states-&gt;committed_page_idx];
&nbsp; &nbsp; //*a0_transport_working_page(lk) = *a0_transport_committed_page(lk); //snowli remove


&nbsp; &nbsp; return A0_OK;
}

**Comment by alephzero** [comment]
Thanks @snowinli for the in-depth analysis!
I'll go through your comments over the next few days and try to understand the corner-cases / race-conditions you described.
If you have the time, it might be easiest for you to make a pull request.

**Comment by snowinli** [comment]
1. Function "a0_transport_timedwait_impl" is lack of&nbsp;a0_transport_lock flow：a0_err_t a0_transport_timedwait_impl（...）{


&nbsp; ***@***.*** modify
&nbsp; &nbsp; &nbsp;while (!lk.transport-&gt;_shutdown) {
&nbsp; &nbsp; if (timeout) {
&nbsp; &nbsp; &nbsp; err = a0_cnd_timedwait(&amp;hdr-&gt;cnd, &amp;hdr-&gt;mtx, *timeout);
&nbsp; &nbsp; &nbsp; if (err == EOWNERDEAD) {
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; a0_mtx_consistent(&amp;hdr-&gt;mtx);
&nbsp; &nbsp; &nbsp; }else if (A0_SYSERR(err) == ETIMEDOUT) {
&nbsp; &nbsp; &nbsp; &nbsp; break;
&nbsp; &nbsp; &nbsp; }
&nbsp; &nbsp; } else {
&nbsp; &nbsp; &nbsp; &nbsp; a0_err_t tmp = a0_cnd_wait(&amp;hdr-&gt;cnd, &amp;hdr-&gt;mtx);
&nbsp; &nbsp; &nbsp; if (tmp == EOWNERDEAD) {
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; a0_mtx_consistent(&amp;hdr-&gt;mtx);
&nbsp; &nbsp; &nbsp; }
&nbsp; &nbsp; }


&nbsp; &nbsp; /*Clear any incomplete changes;*/
&nbsp; &nbsp; *a0_transport_working_page(lk) = *a0_transport_committed_page(lk);
&nbsp; &nbsp; err = a0_predicate_eval(pred, &amp;sat);
&nbsp; &nbsp; if (err | sat) {
&nbsp; &nbsp; &nbsp; break;
&nbsp; &nbsp; }
&nbsp; }/*while*/

...




2. Is "a0_mtx_consistent" correct about lock or cnd_wait?

&nbsp;&nbsp;

**Comment by lshamis** [comment]
@snowinli I'm not able to make it break. The following test passes
```cpp
TEST_CASE_FIXTURE(TransportFixture, "transport] cpp robust wait") {
  a0::Transport transport(a0::cpp_wrap<a0::Arena>(shm.arena));
  auto lk = transport.lock();

  auto frame = lk.alloc(3);
  memcpy(frame.data, "YES", 3);
  lk.commit();

  lk.jump_head();

  a0::test::subproc([this]() {
    std::this_thread::sleep_for(std::chrono::milliseconds(10));
    a0::Transport transport(a0::cpp_wrap<a0::Arena>(shm.arena));
    auto lk = transport.lock();
    // Exit without cleaning resources.
    quick_exit(0);
  });

  a0::test::subproc([this]() {
    std::this_thread::sleep_for(std::chrono::milliseconds(100));
    a0::Transport transport(a0::cpp_wrap<a0::Arena>(shm.arena));
    auto lk = transport.lock();
    auto frame = lk.alloc(3);
    memcpy(frame.data, "YES", 3);
    lk.commit();
  });

  lk.wait([&]() {
    return lk.has_next();
  });

  REQUIRE(lk.has_next());
}
```
